- hosts: goslow
  become: yes
  tasks:
  - name: create github_trending_bot user
    user: name=github_trending_bot

  - name: ensure directory /var/lib/github_trending_bot exists
    file: path=/var/lib/github_trending_bot state=directory

  - name: ensure directory /etc/github_trending_bot exists
    file: path=/etc/github_trending_bot.d state=directory

  - name: copy environment file
    copy: src=environment dest=/etc/github_trending_bot.d/environment

  - name: ensure file /var/lib/github_trending_bot/last_update has content
    copy: content=669203916 dest=/var/lib/github_trending_bot/last_update force=no

  - name: ensure file /var/lib/github_trending_bot/last_update is owned by github_trending_bot
    file: path=/var/lib/github_trending_bot/last_update owner=github_trending_bot

  - name: copy systemd config
    copy: src=github_trending_bot.service dest=/lib/systemd/system/github_trending_bot.service

  - name: installing python package
    pip:
      name: git+https://github.com/alexandershov/github_trending_bot.git
      executable: pip3.6
      editable: false

  - name: ensure service is started
    service: name=github_trending_bot state=started

  - name: ensure service is restarted
    service: name=github_trending_bot state=restarted
